/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrabalhoRouteImport } from './routes/trabalho'
import { Route as SaudeRouteImport } from './routes/saude'
import { Route as RemessasRouteImport } from './routes/remessas'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as PageRouteImport } from './routes/page'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MoradiaRouteImport } from './routes/moradia'
import { Route as MapaRouteImport } from './routes/mapa'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EsqueciSenhaRouteImport } from './routes/esqueci-senha'
import { Route as DocumentosRouteImport } from './routes/documentos'
import { Route as ComunidadeRouteImport } from './routes/comunidade'
import { Route as ChecklistRouteImport } from './routes/checklist'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const TrabalhoRoute = TrabalhoRouteImport.update({
  id: '/trabalho',
  path: '/trabalho',
  getParentRoute: () => rootRouteImport,
} as any)
const SaudeRoute = SaudeRouteImport.update({
  id: '/saude',
  path: '/saude',
  getParentRoute: () => rootRouteImport,
} as any)
const RemessasRoute = RemessasRouteImport.update({
  id: '/remessas',
  path: '/remessas',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const PageRoute = PageRouteImport.update({
  id: '/page',
  path: '/page',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MoradiaRoute = MoradiaRouteImport.update({
  id: '/moradia',
  path: '/moradia',
  getParentRoute: () => rootRouteImport,
} as any)
const MapaRoute = MapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EsqueciSenhaRoute = EsqueciSenhaRouteImport.update({
  id: '/esqueci-senha',
  path: '/esqueci-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentosRoute = DocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunidadeRoute = ComunidadeRouteImport.update({
  id: '/comunidade',
  path: '/comunidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistRoute = ChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/chat': typeof ChatRoute
  '/checklist': typeof ChecklistRoute
  '/comunidade': typeof ComunidadeRoute
  '/documentos': typeof DocumentosRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/login': typeof LoginRoute
  '/mapa': typeof MapaRoute
  '/moradia': typeof MoradiaRoute
  '/onboarding': typeof OnboardingRoute
  '/page': typeof PageRoute
  '/planos': typeof PlanosRoute
  '/profile': typeof ProfileRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/remessas': typeof RemessasRoute
  '/saude': typeof SaudeRoute
  '/trabalho': typeof TrabalhoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/chat': typeof ChatRoute
  '/checklist': typeof ChecklistRoute
  '/comunidade': typeof ComunidadeRoute
  '/documentos': typeof DocumentosRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/login': typeof LoginRoute
  '/mapa': typeof MapaRoute
  '/moradia': typeof MoradiaRoute
  '/onboarding': typeof OnboardingRoute
  '/page': typeof PageRoute
  '/planos': typeof PlanosRoute
  '/profile': typeof ProfileRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/remessas': typeof RemessasRoute
  '/saude': typeof SaudeRoute
  '/trabalho': typeof TrabalhoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/chat': typeof ChatRoute
  '/checklist': typeof ChecklistRoute
  '/comunidade': typeof ComunidadeRoute
  '/documentos': typeof DocumentosRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/login': typeof LoginRoute
  '/mapa': typeof MapaRoute
  '/moradia': typeof MoradiaRoute
  '/onboarding': typeof OnboardingRoute
  '/page': typeof PageRoute
  '/planos': typeof PlanosRoute
  '/profile': typeof ProfileRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/remessas': typeof RemessasRoute
  '/saude': typeof SaudeRoute
  '/trabalho': typeof TrabalhoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/chat'
    | '/checklist'
    | '/comunidade'
    | '/documentos'
    | '/esqueci-senha'
    | '/login'
    | '/mapa'
    | '/moradia'
    | '/onboarding'
    | '/page'
    | '/planos'
    | '/profile'
    | '/redefinir-senha'
    | '/remessas'
    | '/saude'
    | '/trabalho'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/chat'
    | '/checklist'
    | '/comunidade'
    | '/documentos'
    | '/esqueci-senha'
    | '/login'
    | '/mapa'
    | '/moradia'
    | '/onboarding'
    | '/page'
    | '/planos'
    | '/profile'
    | '/redefinir-senha'
    | '/remessas'
    | '/saude'
    | '/trabalho'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/chat'
    | '/checklist'
    | '/comunidade'
    | '/documentos'
    | '/esqueci-senha'
    | '/login'
    | '/mapa'
    | '/moradia'
    | '/onboarding'
    | '/page'
    | '/planos'
    | '/profile'
    | '/redefinir-senha'
    | '/remessas'
    | '/saude'
    | '/trabalho'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ChatRoute: typeof ChatRoute
  ChecklistRoute: typeof ChecklistRoute
  ComunidadeRoute: typeof ComunidadeRoute
  DocumentosRoute: typeof DocumentosRoute
  EsqueciSenhaRoute: typeof EsqueciSenhaRoute
  LoginRoute: typeof LoginRoute
  MapaRoute: typeof MapaRoute
  MoradiaRoute: typeof MoradiaRoute
  OnboardingRoute: typeof OnboardingRoute
  PageRoute: typeof PageRoute
  PlanosRoute: typeof PlanosRoute
  ProfileRoute: typeof ProfileRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  RemessasRoute: typeof RemessasRoute
  SaudeRoute: typeof SaudeRoute
  TrabalhoRoute: typeof TrabalhoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trabalho': {
      id: '/trabalho'
      path: '/trabalho'
      fullPath: '/trabalho'
      preLoaderRoute: typeof TrabalhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saude': {
      id: '/saude'
      path: '/saude'
      fullPath: '/saude'
      preLoaderRoute: typeof SaudeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remessas': {
      id: '/remessas'
      path: '/remessas'
      fullPath: '/remessas'
      preLoaderRoute: typeof RemessasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/page': {
      id: '/page'
      path: '/page'
      fullPath: '/page'
      preLoaderRoute: typeof PageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moradia': {
      id: '/moradia'
      path: '/moradia'
      fullPath: '/moradia'
      preLoaderRoute: typeof MoradiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapa': {
      id: '/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof MapaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esqueci-senha': {
      id: '/esqueci-senha'
      path: '/esqueci-senha'
      fullPath: '/esqueci-senha'
      preLoaderRoute: typeof EsqueciSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentos': {
      id: '/documentos'
      path: '/documentos'
      fullPath: '/documentos'
      preLoaderRoute: typeof DocumentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidade': {
      id: '/comunidade'
      path: '/comunidade'
      fullPath: '/comunidade'
      preLoaderRoute: typeof ComunidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklist': {
      id: '/checklist'
      path: '/checklist'
      fullPath: '/checklist'
      preLoaderRoute: typeof ChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ChatRoute: ChatRoute,
  ChecklistRoute: ChecklistRoute,
  ComunidadeRoute: ComunidadeRoute,
  DocumentosRoute: DocumentosRoute,
  EsqueciSenhaRoute: EsqueciSenhaRoute,
  LoginRoute: LoginRoute,
  MapaRoute: MapaRoute,
  MoradiaRoute: MoradiaRoute,
  OnboardingRoute: OnboardingRoute,
  PageRoute: PageRoute,
  PlanosRoute: PlanosRoute,
  ProfileRoute: ProfileRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  RemessasRoute: RemessasRoute,
  SaudeRoute: SaudeRoute,
  TrabalhoRoute: TrabalhoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
